"""Write web/js/version.js from the current git state.

There is no build step, so the version the customer sees has to be written
into a file. Run this before deploying: it stamps whatever HEAD is at that
moment, which is the commit being deployed.

    python tools/stamp-version.py
"""
import io
import os
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "web", "js", "version.js")


def git(*args):
    return subprocess.check_output(["git", "-C", ROOT, *args], text=True).strip()


commit = git("rev-parse", "--short=7", "HEAD")
date = git("log", "-1", "--format=%cd", "--date=format:%Y-%m-%d")
dirty = bool(git("status", "--porcelain"))

body = (
    "/* Generated by tools/stamp-version.py - do not edit by hand. */\n"
    "export const VERSION = {\n"
    '  commit: "%s%s",\n' % (commit, "+" if dirty else "")
    + '  date: "%s",\n' % date
    + "};\n"
)

io.open(OUT, "w", encoding="utf-8", newline="\n").write(body)
print("stamped %s %s%s" % (date, commit, " (working tree dirty)" if dirty else ""))
